server:
  port: 8088
spring:
  task:
    scheduling:
      pool:
        size: 20
      thread-name-prefix: Scheduled-
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 50
      minimum-idle: 5
      pool-name: HikariPool
    password: 123456
#    password: 1rsD8xDrG8q0KsbJ
    type: com.zaxxer.hikari.HikariDataSource
    #    url: jdbc:mysql://localhost:3306/plank?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    url: jdbc:mysql://122.51.126.37:3306/plank?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root

mybatis-plus:
  configuration:
    cache-enabled: true
    default-executor-type: reuse
    default-statement-timeout: 25000
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
  mapper-locations: classpath:/mapper/*Mapper.xml

emSecSecurityServerUrl: http://127.0.0.1:18888/api/verifyUserInfo?
ocr:
  service: chaojiyingOcrService
  third:
    aliyun:
      appcode: ''
      chaojiying:
        pass: ''
        softid: 0
        user: ''
plank:
  automaticTrading: true
  stopLossRate: 0.94
  takeProfitRate: 1.09
  automaticTradingMoneyLimitUp: 10000
  automaticPlankTrading: false
  automaticPlankTop5Bk: true
  automaticPlankTradingTimeLimit: 10
  singleTransactionLimitAmount: 5000
  stockTurnoverThreshold: 1000000000
  mainFundThreshold: 300000000
  enableMonitor: true
  printName: true
  recentDayNumber: 1
  xueQiuCookie: device_id=a51d1f9867a7ab8b4cd39edf4bb37ce4; remember=1; xq_a_token=69041f023e406b646e08e7f7ea563bde7dfc262b; xqat=69041f023e406b646e08e7f7ea563bde7dfc262b; xq_id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOjU3MzM3MDcyNjEsImlzcyI6InVjIiwiZXhwIjoxNjgyNzgwNjY1LCJjdG0iOjE2ODAyMzE0Njk1NTEsImNpZCI6ImQ5ZDBuNEFadXAifQ.lcb4HKha_4cu-L5B9VDXIL-UPk4t_NvXTw2MDDPQjKHZzTWNt0uWaeQzB3wWgB07luxrHju_7DYH7pwkWY0RcAFPGRnvu-AHwWjziadU1cZqzf1siS_-pMPtCx7mDj60xv5aYuCCybOzCPWopQR-ILl29NGaCJTtMgMK_119B2HS8jLKe797FZRBUvZe-bvUdRo3Kktj_UgZEgcZ_EhZ1OK7uOnoRFELdavu8p77o5sCDfbeBCarsJSI5WwE35wI2YPeD1HYbQ0zSoBvmeN6MApeaPXVlBH0kaY_1FdihPjN15cwyNrLUWA4tHidsD-A1okLAa0Xd9mbh7D-ppOWPQ; xq_r_token=ec51aa82f9fc53562155f32a1294c5d869ac54b6; xq_is_login=1; u=5733707261; acw_tc=2760826516807468645463485ef647086ad63c4bde18490ad10c621ddd9cee; is_overseas=0; Hm_lvt_1db88642e346389874251b5a1eded6e3=1679449018,1679899730,1680746870; Hm_lpvt_1db88642e346389874251b5a1eded6e3=1680746870
  mainFundUrl: https://push2.eastmoney.com/api/qt/clist/get?fid=f62&po=1&pz=6000&pn=1&np=1&fltt=2&invt=2&ut=b2884a393a59ad64002292a3e90d46a5&fs=m:0+t:6+f:!2,m:0+t:13+f:!2,m:0+t:80+f:!2,m:1+t:2+f:!2,m:1+t:23+f:!2&fields=f12,f14,f3,f62,f184,f267,f127,f268,f164,f109,f165,f174,f160,f175
  industryBKUrl: https://push2.eastmoney.com/api/qt/clist/get?cb=jQuery112306145005741278797_1676863228205&fid=f3&po=1&pz=100&pn=1&np=1&fltt=2&invt=2&ut=b2884a393a59ad64002292a3e90d46a5&fs=m%3A90+t%3A2&fields=f12%2Cf14%2Cf2%2Cf3%2Cf62%2Cf184%2Cf66%2Cf69%2Cf72%2Cf75%2Cf78%2Cf81%2Cf84%2Cf87%2Cf204%2Cf205%2Cf124%2Cf1%2Cf13
  conceptBKUrl: https://push2.eastmoney.com/api/qt/clist/get?cb=jQuery112306145005741278797_1676863228203&fid=f3&po=1&pz=100&pn=1&np=1&fltt=2&invt=2&ut=b2884a393a59ad64002292a3e90d46a5&fs=m%3A90+t%3A3&fields=f12%2Cf14%2Cf2%2Cf3%2Cf62%2Cf184%2Cf66%2Cf69%2Cf72%2Cf75%2Cf78%2Cf81%2Cf84%2Cf87%2Cf204%2Cf205%2Cf124%2Cf1%2Cf13
  updateStockBkUrl: https://push2.eastmoney.com/api/qt/clist/get?cb=jQuery112309053343085134742_1676868400492&fid=f62&po=1&pz=100&pn=1&np=1&fltt=2&invt=2&ut=b2884a393a59ad64002292a3e90d46a5&fs=b%3A{BK}&fields=f12%2Cf14%2Cf2%2Cf3%2Cf62%2Cf184%2Cf66%2Cf69%2Cf72%2Cf75%2Cf78%2Cf81%2Cf84%2Cf87%2Cf204%2Cf205%2Cf124%2Cf1%2Cf13
  todayFundTrendUrl: http://stock.xueqiu.com/v5/stock/capital/flow.json?symbol={code}
  xueQiuStockDetailUrl: http://stock.xueqiu.com/v5/stock/chart/kline.json?symbol={code}&begin={time}&period=day&type=before&count=-{recentDayNumber}&indicator=kline,pe,pb,ps,pcf,market_capital,agt,ggt,balance
  foreignShareholdingUrl: https://datacenter-web.eastmoney.com/api/data/v1/get?callback=jQuery112304010956559881589_1675054117441&sortColumns=HOLD_MARKET_CAP&sortTypes=-1&pageSize=500&pageNumber=1&reportName=RPT_MUTUAL_STOCK_NORTHSTA&columns=ALL&source=WEB&client=WEB&filter=(TRADE_DATE%3D%272023-01-20%27)(INTERVAL_TYPE%3D%223%22)
  xueQiuStockLimitUpPriceUrl: https://stock.xueqiu.com/v5/stock/quote.json?symbol={code}&extend=detail

logging:
  level:
    com:
      mistra:
        plank:
          dao: info
